spring:
  application:
    name: demo

  redis:
    host: localhost
    port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  profiles:
    active: ${APP_PROFILE:dev}

crawler:
  inputFile: "./data/links.txt"
  outputDir: "./data-lake"

chunk:
  hash:
    algo: "SHA-256"

ollama:
  url: http://127.0.0.1:${OLLAMA_PORT:11434}
  model:
    chat: "llama3.2:1b"
    embedding: "mxbai-embed-large"

qdrant:
  url: http://127.0.0.1:${QDRANT_PORT:6333}
  collection:
    name: "support-chunks"
    vectorSize: 1024
